sap.ui.jsview("controlreq.MainView", {                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
  /**                                                                                                                                                                                                                                                          
   * Specifies the Controller belonging to this View. In the case that it is                                                                                                                                                                                   
   * not implemented, or that "null" is returned, this View does not have a                                                                                                                                                                                    
   * Controller.                                                                                                                                                                                                                                               
   *&nbsp;                                                                                                                                                                                                                                                     
   * @memberOf controlreq.MainView                                                                                                                                                                                                                             
   */                                                                                                                                                                                                                                                          
  getControllerName : function() {                                                                                                                                                                                                                             
    return "controlreq.MainView";                                                                                                                                                                                                                              
  },                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
  /**                                                                                                                                                                                                                                                          
   * Is initially called once after the Controller has been instantiated. It                                                                                                                                                                                   
   * is the place where the UI is constructed. Since the Controller is given                                                                                                                                                                                   
   * to this method, its event handlers can be attached right away.                                                                                                                                                                                            
   *&nbsp;                                                                                                                                                                                                                                                     
   * @memberOf controlreq.MainView                                                                                                                                                                                                                             
   */                                                                                                                                                                                                                                                          
  createContent : function(oController) {                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                               
    var aControls = [];                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                               
    var oLogoffButton = new sap.m.Button("btnLogoff", {icon:"sap-icon://log" });                                                                                                                                                                               
&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                                                       
    var oLabelRequired = new sap.m.Label("lbl2", {required: true, text:'Cód. Demanda' , labelFor: "fDemanda" });                                                                                                                                               
&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                                                       
    var oField = new sap.m.Input( "fDemanda" );                                                                                                                                                                                                                
                                                                                                                                                                                                                                                               
    var oButton = new sap.m.Button("Buscar", {                                                                                                                                                                                                                 
      text : "Buscar" ,                                                                                                                                                                                                                                        
      type : "Emphasized" ,                                                                                                                                                                                                                                    
      icon : "sap-icon://search"                                                                                                                                                                                                                               
    });                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                               
//    aControls.push( oLogoffButton.attachPress(oController.logoff), oLabelRequired , oField , oButton.attachPress(oController.doIt));                                                                                                                         
    aControls.push( oLabelRequired , oField , oButton.attachPress(oController.doIt));                                                                                                                                                                          
                                                                                                                                                                                                                                                               
    var oRequestTable = new sap.m.Table("tRequests", {                                                                                                                                                                                                         
      inset                  : true,                                                                                                                                                                                                                           
      headerText             : "Lista de Requests",                                                                                                                                                                                                            
      headerDesign           : sap.m.ListHeaderDesign.Standard,                                                                                                                                                                                                
      mode                   : sap.m.ListMode.SingleSelect,                                                                                                                                                                                                    
      includeItemInSelection : false,                                                                                                                                                                                                                          
    });                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                               
    var col1 = new sap.m.Column("col1", {                                                                                                                                                                                                                      
      header : new sap.m.Label({                                                                                                                                                                                                                               
        text : "Código"                                                                                                                                                                                                                                        
      })                                                                                                                                                                                                                                                       
    });                                                                                                                                                                                                                                                        
    oRequestTable.addColumn(col1);                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
    var col2 = new sap.m.Column("col2", {                                                                                                                                                                                                                      
      header : new sap.m.Label({                                                                                                                                                                                                                               
        text : "Descrição"                                                                                                                                                                                                                                     
      })                                                                                                                                                                                                                                                       
    });                                                                                                                                                                                                                                                        
    oRequestTable.addColumn(col2);                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
    var col3 = new sap.m.Column("col3", {                                                                                                                                                                                                                      
      header : new sap.m.Label({                                                                                                                                                                                                                               
        text : "Funcional"                                                                                                                                                                                                                                     
      })                                                                                                                                                                                                                                                       
    });                                                                                                                                                                                                                                                        
    oRequestTable.addColumn(col3);                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
    var col4 = new sap.m.Column("col4", {                                                                                                                                                                                                                      
      header : new sap.m.Label({                                                                                                                                                                                                                               
        text : "DEV"                                                                                                                                                                                                                                           
      })                                                                                                                                                                                                                                                       
    });                                                                                                                                                                                                                                                        
    oRequestTable.addColumn(col4);                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
    var col5 = new sap.m.Column("col5", {                                                                                                                                                                                                                      
      header : new sap.m.Label({                                                                                                                                                                                                                               
        text : "QAS"                                                                                                                                                                                                                                           
      })                                                                                                                                                                                                                                                       
    });                                                                                                                                                                                                                                                        
    oRequestTable.addColumn(col5);                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
    var colItems = new sap.m.ColumnListItem("colItems", { type : "Active" });                                                                                                                                                                                  
                                                                                                                                                                                                                                                               
    oRequestTable.bindAggregation("items", "/RequestSet", colItems);                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
    var txtNAME = new sap.m.Title("txtNAME", { text : "{Trkorr}" });                                                                                                                                                                                           
    colItems.addCell(txtNAME);                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                               
    var txtNAME2 = new sap.m.Text("txtNAME2", { text : "{As4text}" });                                                                                                                                                                                         
    colItems.addCell(txtNAME2);                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                               
    var txtNAME3 = new sap.m.Text("txtNAME3", { text : "{Funcional}" });                                                                                                                                                                                       
    colItems.addCell(txtNAME3);                                                                                                                                                                                                                                
&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                                                                                                       
    var txtNAME4 = new sap.m.CheckBox("txtNAME4", { selected : "{Dev}" , editable : false });                                                                                                                                                                  
    colItems.addCell(txtNAME4);                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                               
    var txtNAME5 = new sap.m.CheckBox("txtNAME5", { selected : "{Qas}" , editable : false });                                                                                                                                                                  
    colItems.addCell(txtNAME5);                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                               
    var Pagina = new sap.m.Page({                                                                                                                                                                                                                              
      title : "Relatório de Request",                                                                                                                                                                                                                          
      content : [ aControls, oRequestTable ]                                                                                                                                                                                                                   
    });                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                               
    return Pagina;                                                                                                                                                                                                                                             
  }                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
});                                                                                                                                                                                                                                                            